# Basic dependabot.yml file with

version: 2
updates:
  # Enable version updates for npm
  - package-ecosystem: "npm"
    directory: "/Client"
    schedule:
      interval: "daily"
      
  # Enable version updates for nuget
  - package-ecosystem: "nuget"
    directory: "/Server"
    schedule:
      interval: "daily"
